GET http://localhost:3000/dosen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lSWQiOiJGYWl6UmlmYWkiLCJyb2xlSWQiOiJkb3NlbiIsImlhdCI6MTY3MjkwNTU5NywiZXhwIjoxNjcyOTA1NjE3fQ.zICy4LvpVdW_pxH8rWU6EI8vPTwDnq4TL9f0JGfev88

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "FaizRifai",
    "password": "1234511",
    "role": "dosen"
}

###
GET http://localhost:3000/token

###
PUT http://localhost:3000/edituser/2
Content-Type: application/json

{
    "username": "FaizRifai5",
    "password": "12345",
    "role": "dosen"
}

###
PUT http://localhost:3000/nilai/14
Content-Type: application/json

{
    "nama": "Faiz Lasiatamq",
    "nilai_harian":80,
    "bobot1": 20,
    "ulangan_tengah": 80,
    "bobot2": 40,
    "ulangan_akhir": 100,
    "bobot3": 40,
    "sks": 4
}

###
DELETE http://localhost:3000/nilai/14
Content-Type: application/json