GET http://localhost:3000/dosen
Authorization: Bearer 

###
DELETE http://localhost:3000/deleteuser
Authorization: Bearer 

###
DELETE http://localhost:3000/deleteuser/22


###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "180535632521",
    "password": "123",
    "role": "adwad"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "1",
    "password": "123",
    "confpassword": "123",
    "role": "dosen"
}
###
DELETE http://localhost:3000/logout

###
GET http://localhost:3000/me
Authorization: Bearer 
###
GET http://localhost:3000/user
###
GET http://localhost:3000/dosen/14
Authorization: Bearer 
###
GET http://localhost:3000/token
###
PUT http://localhost:3000/edituser/2
Content-Type: application/json

{
    "username": "FaizRifai5",
    "password": "12345",
    "role": "dosen"
}

###
POST http://localhost:3000/nilai
Authorization: Bearer 
Content-Type: application/json

{
    "nama": "Faiz Lasiatamq",
    "nim": "180535632521",
    "matakuliah": "B.Indo",
    "nilai_harian":84,
    "bobot1": 20,
    "ulangan_tengah": 80,
    "bobot2": 40,
    "ulangan_akhir": 100,
    "bobot3": 40,
    "sks": 4
}

###
GET http://localhost:3000/nilaisaya
Authorization: Bearer 
###
DELETE http://localhost:3000/nilai/14
Content-Type: application/json
###
DELETE http://localhost:3000/nilai
Content-Type: application/json